[package]
name = "snake_game"
version = "0.1.0"
authors = ["Mateusz Dzierzecki <mateusz@dzierzecki.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
